# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4434db96aff4eeed3a8831b8980c0a98f545a3f90a92d80bc3477127fcfbbe635b733b582be0bd5912312636eb05ee159a06285d1a45adf0965be7e764067bb9

test:
  secret_key_base: 68c81b8934b366adfedea9ce1ebd575053b778ad889b5c2a93ab868e1b97bb1a58332b340ad6149e764dda2e3a05c85018cc55c0802774fcc319e1d9c1df2c9a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
